<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Marca extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Marca_model');
        $this->isLogged();
    } 

    /*
     * Listing of marca
     */
    function index()
    {
        $data['marca'] = $this->Marca_model->get_all_marca();
        
        $data['_view'] = 'marca/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new marca
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'descripcion' => $this->input->post('descripcion'),
				'activo' => $this->input->post('activo'),
            );
            
            $marca_id = $this->Marca_model->add_marca($params);
            redirect('marca/index');
        }
        else
        {            
            $data['_view'] = 'marca/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a marca
     */
    function edit($id_marca)
    {   
        // check if the marca exists before trying to edit it
        $data['marca'] = $this->Marca_model->get_marca($id_marca);
        
        if(isset($data['marca']['id_marca']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descripcion' => $this->input->post('descripcion'),
					'activo' => $this->input->post('activo'),
                );

                $this->Marca_model->update_marca($id_marca,$params);            
                redirect('marca/index');
            }
            else
            {
                $data['_view'] = 'marca/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The marca you are trying to edit does not exist.');
    } 

    /*
     * Deleting marca
     */
    function remove($id_marca)
    {
        $marca = $this->Marca_model->get_marca($id_marca);

        // check if the marca exists before trying to delete it
        if(isset($marca['id_marca']))
        {
            $this->Marca_model->delete_marca($id_marca);
            redirect('marca/index');
        }
        else
            show_error('The marca you are trying to delete does not exist.');
    }
    
}
