<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Producto extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Producto_model');
        $this->isLogged();
    } 

    /*
     * Listing of producto
     */
    function index()
    {
        $data['producto'] = $this->Producto_model->get_all_producto();
        
        $data['_view'] = 'producto/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new producto
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'descripcion' => $this->input->post('descripcion'),
                'cantidad' => $this->input->post('cantidad'),
                'costo' => $this->input->post('costo'),
                'id_categoria' => $this->input->post('id_categoria'),
                'id_marca' => $this->input->post('id_marca'),
                'activo' => $this->input->post('activo'),
            );
            
            $producto_id = $this->Producto_model->add_producto($params);
            redirect('producto/index');
        }
        else
        {            
            $data['categorias'] = $this->Producto_model->get_all_categoria();
            $data['marcas'] = $this->Producto_model->get_all_marca();
            $data['_view'] = 'producto/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a producto
     */
    function edit($id_producto)
    {   
        // check if the producto exists before trying to edit it
        $data['producto'] = $this->Producto_model->get_producto($id_producto);
        
        if(isset($data['producto']['id_producto']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'descripcion' => $this->input->post('descripcion'),
					'cantidad' => $this->input->post('cantidad'),
					'costo' => $this->input->post('costo'),
					'id_categoria' => $this->input->post('id_categoria'),
					'id_marca' => $this->input->post('id_marca'),
					'activo' => $this->input->post('activo'),
                );

                $this->Producto_model->update_producto($id_producto,$params);            
                redirect('producto/index');
            }
            else
            {
                $data['categorias'] = $this->Producto_model->get_all_categoria();
                $data['marcas'] = $this->Producto_model->get_all_marca();
                $data['_view'] = 'producto/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The producto you are trying to edit does not exist.');
    } 

    /*
     * Deleting producto
     */
    function remove($id_producto)
    {
        $producto = $this->Producto_model->get_producto($id_producto);

        // check if the producto exists before trying to delete it
        if(isset($producto['id_producto']))
        {
            $this->Producto_model->delete_producto($id_producto);
            redirect('producto/index');
        }
        else
            show_error('The producto you are trying to delete does not exist.');
    }
    
}
