<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get categoria by id_categoria
     */
    function get_categoria($id_categoria)
    {
        return $this->db->get_where('categoria',array('id_categoria'=>$id_categoria))->row_array();
    }
        
    /*
     * Get all categoria
     */
    function get_all_categoria()
    {
        $this->db->order_by('id_categoria', 'desc');
        return $this->db->get('categoria')->result_array();
    }
        
    /*
     * function to add new categoria
     */
    function add_categoria($params)
    {
        $this->db->trans_start();
        $this->db->insert('categoria', $params);
        $insert_id = $this->db->insert_id();
        $this->db->trans_complete();

        return $insert_id;
    }
    
    /*
     * function to update categoria
     */
    function update_categoria($id_categoria,$params)
    {
        $this->db->trans_start();
        $this->db->where('id_categoria',$id_categoria);
        $valor = $this->db->update('categoria',$params);
        $this->db->trans_complete();

        return $valor;
    }
    
    /*
     * function to delete categoria
     */
    function delete_categoria($id_categoria)
    {
        //return $this->db->delete('categoria',array('id_categoria'=>$id_categoria));
        $this->db->trans_start();
        $this->db->where('id_categoria',$id_categoria);
        $params = array(
            'activo' => 0,
        );
        $valor = $this->db->update('categoria',$params);
        $this->db->trans_complete();

        return $valor;
    }
}
