<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Marca_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get marca by id_marca
     */
    function get_marca($id_marca)
    {
        return $this->db->get_where('marca',array('id_marca'=>$id_marca))->row_array();
    }
        
    /*
     * Get all marca
     */
    function get_all_marca()
    {
        $this->db->order_by('id_marca', 'desc');
        return $this->db->get('marca')->result_array();
    }
        
    /*
     * function to add new marca
     */
    function add_marca($params)
    {
        $this->db->trans_start();
        $this->db->insert('marca', $params);
        $insert_id = $this->db->insert_id();
        $this->db->trans_complete();

        return $insert_id;
    }
    
    /*
     * function to update marca
     */
    function update_marca($id_marca,$params)
    {
        $this->db->trans_start();
        $this->db->where('id_marca',$id_marca);
        $valor = $this->db->update('marca',$params);
        $this->db->trans_complete();

        return $valor;
    }
    
    /*
     * function to delete marca
     */
    function delete_marca($id_marca)
    {
        //return $this->db->delete('marca',array('id_marca'=>$id_marca));
        $this->db->trans_start();
        $this->db->where('id_marca',$id_marca);
        $params = array(
            'activo' => 0,
        );
        $valor = $this->db->update('marca',$params);
        $this->db->trans_complete();

        return $valor;
    }
}
